# Generated by Django 5.2.7 on 2025-10-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('average_land_holding', models.FloatField()),
                ('irrigation_type', models.CharField(max_length=100)),
                ('dominant_crops', models.CharField(max_length=200)),
                ('rainfall', models.FloatField()),
                ('yield_per_hectare', models.FloatField()),
            ],
        ),
    ]
