# Generated by Django 5.2.7 on 2025-10-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_region_irrigation_area_region_land_holding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroppingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('total_geographical_area', models.FloatField(blank=True, null=True)),
                ('reporting_area', models.FloatField(blank=True, null=True)),
                ('forests', models.FloatField(blank=True, null=True)),
                ('not_available_for_cultivation', models.FloatField(blank=True, null=True)),
                ('permanent_pastures', models.FloatField(blank=True, null=True)),
                ('tree_crops_and_groves', models.FloatField(blank=True, null=True)),
                ('culturable_wasteland', models.FloatField(blank=True, null=True)),
                ('fallow_other_than_current', models.FloatField(blank=True, null=True)),
                ('current_fallows', models.FloatField(blank=True, null=True)),
                ('net_area_sown', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
