# Generated by Django 5.2.7 on 2025-10-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_croppingstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('kharif_area', models.FloatField(blank=True, null=True)),
                ('rabi_area', models.FloatField(blank=True, null=True)),
                ('perennial_area', models.FloatField(blank=True, null=True)),
                ('others_area', models.FloatField(blank=True, null=True)),
                ('total_area', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
