# Generated by Django 5.2.7 on 2025-10-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_irrigationarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('holding', 'Land Holding'), ('irrigation', 'Irrigation'), ('cropping', 'Cropping')], max_length=20)),
                ('image', models.FileField(upload_to='gallery/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
